MEC Production/MEC Production/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Enter PO Validity standard number of days</inlineHelpText>
        <label>PO Validity (in days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the SAP Account ID / Customer Code</inlineHelpText>
        <label>SAP ID / Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>DDS</fullName>
        <active>true</active>
        <description>DDS Accounts created by Sales users and not Synced with SAP</description>
        <label>DDS</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Should be Approved before the RFPO/PO can be generated</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Contact:  send RFPO to this contact</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>RFPO Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Kindly enter here the Client PO Validity as per their PO</inlineHelpText>
        <label>PO Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit limit Exceeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit status is blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>PO</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>PO_Qty__c</fullName>
        <label>PO Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RFPO_Qty__c</fullName>
        <label>RFPO Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MEC Production/MEC Production/src/objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>ProMap-{0000}</displayFormat>
        <label>Product Mapping Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/classes/OpportunityProductsTrigger_Test.cls
@isTest
public class OpportunityProductsTrigger_Test {
    static testmethod void testInsertUpdateOpportunityProducts(){
         Product2 prod = new Product2(Name = 'Laptop X200', 
            Family = 'Hardware');
        insert prod;
       
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
       
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
     
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
         string idd;
         Id accountRecordRypeDDS = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('DDS').getRecordTypeId();
         
         Account account = new Account(Name='Test Account 1',
                                       CurrencyIsoCode='SAR',
                                       RecordTypeId=accountRecordRypeDDS,
                                       SAP_ID__c='479837934001',
                                       Price_Book__c=customPB.Id);
         
         insert account;
        
        Contact NewContact = new Contact (
						FirstName = 'xyzFirst',
						LastName = 'XyZLast',
						AccountId = account.Id,
						Email = 'xyzmail@mail.com');
        
		insert NewContact;

         Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PO').getRecordTypeId();
         Opportunity O = new Opportunity(Approval_Status__c='PO Approved',
                                          AccountId=account.Id,
                                          Name='Opp Test 1',
                                          Contact__c=NewContact.Id,
                                          StageName='new',
                                          RecordTypeId=devRecordTypeId,
                                          CloseDate=date.ValueOf('2007-07-21'),
                                          Amount=100,
                                          Expiry_Date__c=date.ValueOf('2007-07-21'),
                                          Due_Date__c=date.ValueOf('2007-07-21'),
                                          PO_Validity__c=date.ValueOf('2007-07-21'),
                                          Rejection_Reason__c='Overdue Payments');
         
         insert O;
        
        Product_Mapping__c productMappingObj = new Product_Mapping__c(product__c=prod.Id,Account__c=account.Id);
        insert productMappingObj;
        
        List<OpportunityLineItem> oppLineItems = new List<OpportunityLineItem>();
        
		OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=O.id,PriceBookEntryID=customPrice.id, quantity=4, totalprice=200);
        OpportunityLineItem lineItem2 = new OpportunityLineItem (OpportunityID=O.id,UnitPrice=123.00, Quantity=1,Description=null, Discount=100, PricebookEntryId=customPrice.Id);

        OpportunityLineItem lineItem3 = new OpportunityLineItem (OpportunityID=O.id,UnitPrice=100,RFPO_Qty__c=1000,PriceBookEntryID=customPrice.id, quantity=6);
        OpportunityLineItem lineItem4 = new OpportunityLineItem (OpportunityID=O.id,UnitPrice=300,PO_Qty__c=2000,PriceBookEntryID=customPrice.id, quantity=7);
        OpportunityLineItem lineItem6 = new OpportunityLineItem (OpportunityID=O.id,PriceBookEntryID=customPrice.id, quantity=9, totalprice=2005);
        OpportunityLineItem lineItem7 = new OpportunityLineItem (OpportunityID=O.id,PriceBookEntryID=customPrice.id, quantity=10, totalprice=2006);
        
        oppLineItems.add(lineItem1);
        oppLineItems.add(lineItem2);
        oppLineItems.add(lineItem3);
        oppLineItems.add(lineItem4);
        oppLineItems.add(lineItem6);
        oppLineItems.add(lineItem7);
        
 		insert oppLineItems;        
    }
}