MEC Production/MEC Production/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Enter PO Validity standard number of days</inlineHelpText>
        <label>PO Validity (in days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Should be Approved before the RFPO/PO can be generated</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>RFPO Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Kindly enter here the Client PO Validity as per their PO</inlineHelpText>
        <label>PO Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit limit Exceeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit status is blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>IF(AND(RecordType.Name==&apos;RFPO&apos;,ISPICKVAL(Approval_Status__c, &apos;Not Approved&apos;)),&apos;RFPO&apos;, 
IF(AND(RecordType.Name==&apos;RFPO&apos;,ISPICKVAL(Approval_Status__c, &apos;Submitted&apos;)), &apos;RFPO Submitted&apos;, 
IF(AND(RecordType.Name==&apos;PO&apos;,ISPICKVAL(Approval_Status__c,&apos;Not Approved&apos;)),&apos;PO&apos;,
IF(AND(RecordType.Name==&apos;PO&apos;,ISPICKVAL(Approval_Status__c,&apos;Submitted&apos;)),&apos;PO Submitted&apos;,
IF(AND(RecordType.Name==&apos;PO&apos;,ISPICKVAL(Approval_Status__c, &apos;PO Approved&apos;)), &apos;PO-Filled&apos;,&apos;Rejected&apos;)))))</formula>
        <label>RFPO/PO Stage</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>PO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>PO</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

MEC Production/MEC Production/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <label>PO Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit limit Exceeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit status is blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/classes/ConvertToSalesOrder.cls
global class ConvertToSalesOrder{
    
    webservice static String Convert(string OppID)
    {                  
        Opportunity O = [SELECT ID,
                         Approval_Status__c,
                         Stage__c,
                         Amount,
                         name,
                         Pricebook2Id,
                         Due_Date__c,
                         PO_Validity__c,
                         Rejection_Reason__c,
                         Expiry_Date__c,
                         ContractId,
                         AccountId, Account.name from Opportunity Where ID=:OppID];  
                                        
        if(O.Approval_Status__c=='PO Approved')
        {
            if(O.Stage__c=='PO- Partial Filled' || O.Stage__c=='PO-Filled')
            {
                
                try{
                
                    Map<Id, Quote> quotes = new Map<Id, Quote>();
                    Map<Id, List<QuoteLineItem>> quoteItems = new Map<Id, List<QuoteLineItem>>();
                    
                    List<OpportunityLineItem> POList =[select Id,Outlet__c,Outlet__r.name,Product2Id,ListPrice,UnitPrice,Quantity,pricebookentryId from OpportunityLineItem where OpportunityId=:OppID];
                    
                    for(OpportunityLineItem OL : POList)
                    {
                         if(quotes.get(OL.Outlet__c)==null){
                             Quote q = new Quote();
                             q.name = 'Quote-'+OL.Outlet__r.name+'-' + o.name;
                             q.opportunityId = o.id;
                             q.Pricebook2Id = o.Pricebook2Id;
                             q.integration_status__c = 'Pending'; 
                             q.ExpirationDate = System.today().addDays(7);
                             quotes.put(OL.Outlet__c,q);    
                         }
                         if(quoteItems.get(OL.Outlet__c)==null){
                             quoteItems.put(OL.Outlet__c, new List<QuoteLineItem>());
                         }
                         QuoteLineItem qutlineitem = new QuoteLineItem(Product2Id = OL.Product2Id,
                             Quantity = OL.Quantity , UnitPrice = OL.UnitPrice , PricebookEntryId = OL.pricebookentryId,
                             Outlet__c = OL.Outlet__c);
                         quoteItems.get(OL.Outlet__c).add(qutlineitem);
                    }
                    
                    insert quotes.values();
                    
                    for(Id key : quotes.keySet()){
                        for(integer j=0;j<quoteItems.get(key).size();j++){
                            quoteItems.get(key)[j].quoteId = quotes.get(key).id;
                        }
                        insert quoteItems.get(key);    
                    }
                    
                    return 'Quotations are created Successfully!';
                    //pageRef = new PageReference('/'+Ord.ID);                   
                    
                    //Sending email
                    //Messaging.reserveSingleEmailCapacity(2);
                    //Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();                    
                    //User UserEmail = [select id,email from User where username='cloudconcept@mec.com.dev'];
                    //String[] toAddresses = new String[]{UserEmail.email};
                    //mail.setTargetObjectId(UserEmail.id);
                    //mail.setWhatId(Ord.ID);
                    //mail.setUseSignature(false);                    
                    //mail.setBccSender(false);
                    //mail.setSaveAsActivity(false);
                    //mail.setUseSignature(false);
                    //mail.setReplyTo(UserEmail.email);
                    //mail.setToAddresses(toAddresses);
                    //mail.setSenderDisplayName('Order Verfication');                    
                    //EmailTemplate et=[Select id from EmailTemplate where DeveloperName=:'New_Sales_Order_Created'];
                    //mail.setTemplateId(et.id);
                    //Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
                    //system.debug('Email sent');
                    
                }catch(DmlException e) {
                    System.debug('An unexpected error has occurred: ' + e.getMessage());
                    system.debug(e);
                    System.debug('Exception => '+ e.getMessage() + ' : Line Number => '+ e.getLineNumber());
                    return e.getMessage();
                } 
            }
           
        }
        else
        {
            return 'Stage must be Approved';
        }
        return '';
    }    
}