MEC Production/MEC Production/src/objects/Customer_Category_Classfication__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Customer_Category_Classfications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Level__c</fullName>
        <globalPicklist>Classification_Level</globalPicklist>
        <label>Classification Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <label>Customer Category Classification</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>Customer Category Classfication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Category Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MDA&apos;,&apos;Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCA&apos;,&apos;TV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCB&apos;,&apos;HV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCC&apos;,&apos;HIFI&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCD&apos;,&apos;PIC&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCE&apos;,&apos;PVC&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAC&apos;,&apos;Ace IT&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCF&apos;,&apos;PA&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAD&apos;,&apos;Ace P&amp;S&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAE&apos;,&apos;Ace Tab&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAG&apos;,&apos;AceGaming&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAT&apos;,&apos;Ace Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCG&apos;,&apos;ME&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCH&apos;,&apos;BNP&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MIA&apos;,&apos;IT&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRT&apos;,&apos;Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MSM&apos;,&apos;Sony Mobiles&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MSS&apos;,&apos;SONY&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRI&apos;,&apos;Camera&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRG&apos;,&apos;Gaming&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRL&apos;,&apos;AV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRP&apos;,&apos;Portable Media&apos;, 
&apos;Others&apos; 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
</CustomObject>

MEC Production/MEC Production/src/objects/Sell_Out__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sell Outs</relationshipLabel>
        <relationshipName>Sell_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sell_Out__c</fullName>
        <label>Sell Out</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sell Out</label>
    <nameField>
        <displayFormat>SN-{0000000000}</displayFormat>
        <label>Sell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sell Outs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Stock__c.object
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>SN-{0000000000}</displayFormat>
        <label>Stock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/classes/AddSellOut.cls
public class AddSellOut{
    
    public Account RelatedAccount{get;set;}

    Public List<Wrapper> SearchResult{get;set;}
    Public List<Wrapper> AllSearchResult{get;set;}
    Public List<SearchWrapper> SearchCriteria{get;set;}
    
    
     public AddSellOut(ApexPages.standardController std) {
         
        RelatedAccount = (Account)std.getRecord();
        SearchCriteria = new List<SearchWrapper>();
        
        
     
     
     
     }
     
     Public Void getSearchCriteria(){
        List<Customer_Category_Classfication__c> CustomerCategoryClassficationS = [Select Id, Classification_Level__c, Product_Category__c From Customer_Category_Classfication__c Where Account__c =: RelatedAccount.Id];
        //fill SearchCriteria wrapper
        SearchCriteria = new List<SearchWrapper>();
        for(Customer_Category_Classfication__c ccc: CustomerCategoryClassficationS){
            SearchCriteria.add(new SearchWrapper(True, ccc.Product_Category__c, ccc.Classification_Level__c));
        }
    }
    
      Public Void doSearch(){
      
      
      
      }
    
    
     public Class Wrapper{
        public Boolean isSelected {get;set;}
        Public Product2 Prod {get;set;}
        public Account Acc {get;set;}
        public Decimal recommendedRFPO {get;set;}
        
        public Sell_Out__c sellOut {get;set;} 
        public Stock__c stock {get;set;} 

        Public Wrapper(Boolean isSelected, Account Acc, Product2 Prod){
            this.isSelected = isSelected;
            this.Acc = Acc;
            this.Prod = Prod;
            recommendedRFPO = 0;
            
        }
    }
    
       public Class SearchWrapper{
        public Boolean isSelected {get;set;}
        public String Category {get;set;}
        public String Classification {get;set;}
        Public SearchWrapper(Boolean isSelected, String Category, String Classification){
            this.isSelected = isSelected;
            this.Category = Category;
            this.Classification = Classification;
        }
    }
    



}