MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the SAP Account ID / Customer Code</inlineHelpText>
        <label>SAP ID / Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Sell_In_Qty__c</fullName>
        <label>Sell In Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MEC Production/MEC Production/src/objects/Sell_Out__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sell Outs</relationshipLabel>
        <relationshipName>Sell_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sell Outs</relationshipLabel>
        <relationshipName>Sell_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sell_Out__c</fullName>
        <label>Sell Out</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_on_Hand__c</fullName>
        <label>Stock on Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sell Out</label>
    <nameField>
        <displayFormat>SN-{0000000000}</displayFormat>
        <label>Sell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sell Outs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/classes/SellOutTrigger_Test.cls
@isTest
public class SellOutTrigger_Test {
    static testmethod void testInsertUpdateSellOutObject(){
        
        Product2 prod = new Product2(Name = 'Laptop X300', 
            Family = 'Hardware',Sell_In_Qty__c=100);
        insert prod;
       
        Id pricebookId = Test.getStandardPricebookId();
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        
      
        
          
        Account account = new Account(Name='Test Account 1',
                                       CurrencyIsoCode='SAR',
                                       SAP_ID__c='479837934001',
                                       Price_Book__c=customPB.Id);
        
        insert account;
        
        Sell_Out__c sellOutObj = new Sell_Out__c();
        sellOutObj.Account__c = account.Id;
        sellOutObj.Product__c = prod.Id;
        sellOutObj.Week__c = '1';
        sellOutObj.Stock_on_Hand__c = 10;
        
        insert sellOutObj;
        
        sellOutObj.Week__c='4';
        
        update sellOutObj;
    }
}