MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Enter PO Validity standard number of days</inlineHelpText>
        <label>PO Validity (in days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the SAP Account ID / Customer Code</inlineHelpText>
        <label>SAP ID / Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>DDS</fullName>
        <active>true</active>
        <description>DDS Accounts created by Sales users and not Synced with SAP</description>
        <label>DDS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Should be Approved before the RFPO/PO can be generated</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>RFPO Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Kindly enter here the Client PO Validity as per their PO</inlineHelpText>
        <label>PO Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit limit Exceeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit status is blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>PO</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFPO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>RFPO</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/classes/ConvertToSalesOrder_Test.cls
@isTest
public class ConvertToSalesOrder_Test {
    
    static testMethod void insertOrder() {
        
      Product2 prod = new Product2(Name = 'Laptop X200', 
            Family = 'Hardware');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
         
         string idd;
         Id accountRecordRypeDDS = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('DDS').getRecordTypeId();
         
         Account account = new Account(Name='Test Account 1',
                                       CurrencyIsoCode='SAR',
                                       RecordTypeId=accountRecordRypeDDS,
                                       SAP_ID__c='479837934001',
                                       Price_Book__c=customPB.Id);
         
         insert account;
         
         Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('PO').getRecordTypeId();
         
         Opportunity O = new Opportunity(Approval_Status__c='PO Approved',
                                          AccountId=account.Id,
                                          Name='Opp Test 1',
                                          StageName='new',
                                          RecordTypeId=devRecordTypeId,
                                          CloseDate=date.ValueOf('2007-07-21'),
                                          Amount=100,
                                          Expiry_Date__c=date.ValueOf('2007-07-21'),
                                          Due_Date__c=date.ValueOf('2007-07-21'),
                                          PO_Validity__c=date.ValueOf('2007-07-21'),
                                          Rejection_Reason__c='Overdue Payments');
         
         insert O;
         
		 OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=O.id,PriceBookEntryID=customPrice.id, quantity=4, totalprice=200);
         insert lineItem1;
         
         ConvertToSalesOrder.Convert(O.Id);
     }
    
    static testMethod void insertOrder2(){
        
         Id accountRecordRypeDDS = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('DDS').getRecordTypeId();
         
         Account account = new Account(Name='Test Account 1',
                                       CurrencyIsoCode='SAR',
                                       RecordTypeId=accountRecordRypeDDS,
                                       SAP_ID__c='479837934001');
        
        insert account;
       
         Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('RFPO').getRecordTypeId();
        
         Opportunity O = new Opportunity(Approval_Status__c='Not Approved',
                                          AccountId=account.Id,
                                          Name='Opp Test 1',
                                          StageName='new',
                                          RecordTypeId=devRecordTypeId,
                                          CloseDate=date.ValueOf('2007-07-21'),
                                          Amount=100,
                                          Expiry_Date__c=date.ValueOf('2007-07-21'),
                                          Due_Date__c=date.ValueOf('2007-07-21'),
                                          PO_Validity__c=date.ValueOf('2007-07-21'),
                                          Rejection_Reason__c='Overdue Payments');
         
         insert O;
         
         ConvertToSalesOrder.Convert(O.Id);
    }
    
}