MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Enter PO Validity standard number of days</inlineHelpText>
        <label>PO Validity (in days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the SAP Account ID / Customer Code</inlineHelpText>
        <label>SAP ID / Customer Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <inlineHelpText>Should be Approved before the RFPO/PO can be generated</inlineHelpText>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Approved</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>RFPO Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Validity__c</fullName>
        <inlineHelpText>Kindly enter here the Client PO Validity as per their PO</inlineHelpText>
        <label>PO Validity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Overdue Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit limit Exceeded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit status is blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>PO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>PO</label>
    </recordTypes>
    <recordTypes>
        <fullName>RFPO</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>RFPO</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

MEC Production/MEC Production/src/objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>code__c</fullName>
        <label>Client Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>ProMap-{0000}</displayFormat>
        <label>Product Mapping Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/classes/POLoadController_Test.cls
@isTest(seeAllData=true)
public class POLoadController_Test {

    static testMethod void testUploadExtraFile(){
        //Create your product
        Product2 prod = new Product2(
             Name = 'Product X',
             isActive = true
        );
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntryStd = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod.Id,
             UnitPrice = 100.00,
             IsActive = true
        );
        insert pbEntryStd;
        
        
        Account accObj = new Account(Name='Extraa', SAP_ID__c ='Test_MEC',Price_Book__c=pricebookId);    
        insert accObj;
        
        Account childAccObj = new Account(Name='KS1', SAP_ID__c ='Test_MEC_2',Price_Book__c=pricebookId,ParentId=accObj.Id);
        insert childAccObj;
        
        Product_Mapping__c pm = new Product_Mapping__c(Account__c=accObj.Id,Product__c=prod.Id,code__c='001787421');
        insert pm;
        
        Test.startTest();
        Test.setCurrentPage(Page.vfPOLoad);
        
        POLoadController ctrl = new POLoadController();
        ctrl.tmpContact.AccountId = accObj.Id;
        
        ctrl.importCSVFile();
        
        String str = 'Oracle No.,ITEM_DESCRIPTION,KS1' +  '\n'
                        + '001787421,"KDL-50W800C--Sony 50"" Android Bravia 3D LED Full HD TV",7';
        
        ctrl.csvFileBody = Blob.valueOf(str);
        ctrl.importCSVFile();
        ctrl.upload();
        System.assertNotEquals(null,ctrl.prodList);
    
        Test.stopTest();
    }
    
    static testMethod void testUploadVirginFile(){
        //Create your product
        Product2 prod = new Product2(
             Name = 'Product X',
             isActive = true
        );
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntryStd = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod.Id,
             UnitPrice = 100.00,
             IsActive = true
        );
        insert pbEntryStd;
        
        
    
        Account accObj = new Account(Name='Virgin', SAP_ID__c ='Test_MEC',Price_Book__c=pricebookId);    
        insert accObj;
     
        Product_Mapping__c pm = new Product_Mapping__c(Account__c=accObj.Id,Product__c=prod.Id,code__c='302009');
        insert pm;
     
        Test.startTest();
        Test.setCurrentPage(Page.vfPOLoad);
        
        POLoadController ctrl = new POLoadController();
        ctrl.tmpContact.AccountId = accObj.Id;
        
        String str = 'STORE NUMBER,Store Name,VENDOR NUM,Vendor Name,PO NUMBER,SKU NUMBER,Artist Name,Title,Short Name,Vendorss Number,Diffuser,Manuf/Label,UPC CODE,QTY REQUEST,CURRENT COST' +  '\n'
                        + '202,VIRGIN RED SEA MALL           ,302009,SONY MULTIMEDIA KSA FAISALIAH GRP  ,425932,475418,                         ,DS4 CONTROLLER SILVER                             ,ACCESSOR,CUHZCT1SILVER  ,32009,SO.MU,7.1172E+11,10,222';
        
        ctrl.csvFileBody = Blob.valueOf(str);
        ctrl.importCSVFile();
        ctrl.upload();
        
        
        Test.stopTest();
    }
    
    static testMethod void testUploadExtraFile2(){//User selects OPP
        //Create your product
        Product2 prod = new Product2(
             Name = 'Product X',
             isActive = true
        );
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntryStd = new PricebookEntry(
             Pricebook2Id = pricebookId,
             Product2Id = prod.Id,
             UnitPrice = 100.00,
             IsActive = true
        );
        insert pbEntryStd;
        
        
        Account accObj = new Account(Name='Extraa', SAP_ID__c ='Test_MEC',Price_Book__c=pricebookId);    
        insert accObj;
        
        Account childAccObj = new Account(Name='KS1', SAP_ID__c ='Test_MEC_2',Price_Book__c=pricebookId,ParentId=accObj.Id);
        insert childAccObj;
        
        Product_Mapping__c pm = new Product_Mapping__c(Account__c=accObj.Id,Product__c=prod.Id,code__c='001787421');
        insert pm;
        
        
        Id devRecordTypeIdRFPO = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('RFPO').getRecordTypeId();
        
        Opportunity O2 = new Opportunity(Approval_Status__c='PO Approved',
                                          AccountId=accObj.Id,
                                          Name='Opp Test 1',
                                          StageName='new',
                                          RecordTypeId=devRecordTypeIdRFPO,
                                          CloseDate=date.ValueOf('2007-07-21'),
                                          Amount=100,
                                          Expiry_Date__c=date.ValueOf('2007-07-21'),
                                          Due_Date__c=date.ValueOf('2007-07-21'),
                                          PO_Validity__c=date.ValueOf('2007-07-21'),
                                          Rejection_Reason__c='Overdue Payments');
         
         insert O2;
         
         OpportunityLineItem lineItem1 = new OpportunityLineItem (OpportunityID=O2.id,PriceBookEntryID=pbEntryStd.id, quantity=4, totalprice=200,outlet__c=accObj.Id);
        insert lineItem1;
        
        Test.startTest();
        Test.setCurrentPage(Page.vfPOLoad);
        
        POLoadController ctrl = new POLoadController();
        ctrl.tmpContact.AccountId = accObj.Id;
        ctrl.tmpObject.Opportunity__c = O2.id;
        
        ctrl.importCSVFile();
        
        String str = 'Oracle No.,ITEM_DESCRIPTION,KS1' +  '\n'
                        + '001787421,"KDL-50W800C--Sony 50"" Android Bravia 3D LED Full HD TV",7';
        
        ctrl.csvFileBody = Blob.valueOf(str);
        ctrl.importCSVFile();
        ctrl.upload();
        System.assertNotEquals(null,ctrl.prodList);
    
        Test.stopTest();
    }
}