MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hi-Fi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eloc</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Customer_Category_Classfication__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Customer_Category_Classfications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification_Level__c</fullName>
        <globalPicklist>Classification_Level</globalPicklist>
        <label>Classification Level</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <label>Customer Category Classification</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>Customer Category Classfication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Category Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Qty__c</fullName>
        <label>PO Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Id__c</fullName>
        <label>Product Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Mapping_code__c</fullName>
        <label>Product Mapping code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RFPO_Qty__c</fullName>
        <label>RFPO Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weighted_Sell_Out__c</fullName>
        <label>Weighted Sell Out</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Classification_Level__c</fullName>
        <formula>IF(P__c = &apos;Mobile&apos;, 
IF(U__c &lt; 599 ,&apos;D&apos;, 
IF(U__c &lt; 1000,&apos;C&apos;, 
IF(U__c &lt; 1500,&apos;B&apos;, 
IF(U__c &gt; 1500,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c =&apos;TV&apos;, 
IF(U__c &lt; 1500 ,&apos;D&apos;, 
IF(U__c &lt; 5000,&apos;C&apos;, 
IF(U__c &lt; 10000,&apos;B&apos;, 
IF(U__c &gt; 10000,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c =&apos;HV&apos;, 
IF(U__c &lt; 500 ,&apos;D&apos;, 
IF(U__c &lt; 700,&apos;C&apos;, 
IF(U__c &lt; 1000,&apos;B&apos;, 
IF(U__c &gt; 1000,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c =&apos;HIFI&apos; || P__c =&apos;AC&apos;, 
IF(U__c &lt; 1000 ,&apos;D&apos;, 
IF(U__c &lt; 2000,&apos;C&apos;, 
IF(U__c &lt; 3000,&apos;B&apos;, 
IF(U__c &gt; 3000,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c=&apos;ME&apos; || P__c=&apos;CH&apos;|| P__c=&apos;BenQ&apos; || P__c=&apos;RME&apos;, 
IF(U__c&lt;500 ,&apos;D&apos;, 
IF(U__c&lt;700,&apos;C&apos;, 
IF(U__c&lt;1000,&apos;B&apos;, 
IF(U__c&gt;1000,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c=&apos;PSX&apos;, 
IF(U__c&lt;1000 ,&apos;D&apos;, 
IF(U__c&lt;1500,&apos;C&apos;, 
IF(U__c&lt;2500,&apos;B&apos;, 
IF(U__c&gt;2500,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c=&apos;Lenovo&apos;,
IF(U__c&lt;1000 ,&apos;D&apos;, 
IF(U__c&lt;1500,&apos;C&apos;, 
IF(U__c&lt;2500,&apos;B&apos;, 
IF(U__c&gt;2500,&apos;A&apos;,&apos;&apos;)))) 
,IF(P__c=&apos;PIC&apos; || P__c=&apos;PVC&apos; || P__c=&apos;Elux&apos;, 
IF(U__c&lt;1000 ,&apos;D&apos;, 
IF(U__c&lt;2000,&apos;C&apos;, 
IF(U__c&lt;4000,&apos;B&apos;, 
IF(U__c&gt;4000,&apos;A&apos;,&apos;&apos;))))
,
IF(P__c=&apos;BNP&apos;, 
IF(U__c&lt;1000 ,&apos;D&apos;, 
IF(U__c&lt;1500,&apos;C&apos;, 
IF(U__c&lt;1999,&apos;B&apos;, 
IF(U__c&gt;1999,&apos;A&apos;,&apos;&apos;))))
,
IF(P__c=&apos;PA&apos;, 
IF(U__c&lt;2000 ,&apos;D&apos;, 
IF(U__c&lt;700,&apos;C&apos;, 
IF(U__c&lt;1500,&apos;B&apos;, 
IF(U__c&gt;1500,&apos;A&apos;,&apos;&apos;))))
,&apos;&apos;
) 
) 
) 
) 
) 
) 
) 
) 
) 
)</formula>
        <inlineHelpText>Show Classification Level of following Product Category
Mobile
TV
HV
HIFI
PIC
PVC
PA
RME
BNP</inlineHelpText>
        <label>Classification Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Item_Status_Description__c</fullName>
        <formula>IF( TEXT(Item_Status__c) = &apos;A&apos;,&apos;Active&apos;,
IF(TEXT(Item_Status__c) = &apos;C&apos;,&apos;End Of Life&apos;,
IF(TEXT(Item_Status__c) = &apos;B&apos;,&apos;Non Active&apos;,&apos;&apos;
)
)
)</formula>
        <label>Item Status Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Status__c</fullName>
        <label>Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Latest_Stock__c</fullName>
        <label>Latest Stock</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Type__c</fullName>
        <label>Manufacturing Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchandise_Category__c</fullName>
        <label>Merchandise Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <formula>IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MDA&apos;,&apos;Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCA&apos;,&apos;TV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCB&apos;,&apos;HV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCC&apos;,&apos;HIFI&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCD&apos;,&apos;PIC&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCE&apos;,&apos;PVC&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAC&apos;,&apos;Ace IT&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCF&apos;,&apos;PA&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAD&apos;,&apos;Ace P&amp;S&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAE&apos;,&apos;Ace Tab&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAG&apos;,&apos;AceGaming&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MAT&apos;,&apos;Ace Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCG&apos;,&apos;ME&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MCH&apos;,&apos;BNP&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MIA&apos;,&apos;IT&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRT&apos;,&apos;Mobile&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MSM&apos;,&apos;Sony Mobiles&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MSS&apos;,&apos;SONY&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRI&apos;,&apos;Camera&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRG&apos;,&apos;Gaming&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRL&apos;,&apos;AV&apos;, 
IF( MID( Product_Hierarchy__c , 1, 3) =&apos;MRP&apos;,&apos;Portable Media&apos;, 
&apos;Others&apos; 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchandise Hierarchy</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Product_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Classification_Level__c</fullName>
        <label>Classification Level</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Classification</relationshipLabel>
        <relationshipName>Product_Classification</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Classification</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Product Classification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Classification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/objects/Product_Hierarchy__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Product_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products Mapping</relationshipLabel>
        <relationshipName>Products_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>code__c</fullName>
        <label>Client Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Product Mapping</label>
    <nameField>
        <displayFormat>ProMap-{0000}</displayFormat>
        <label>Product Mapping Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Production/MEC Production/src/objects/Sell_Out__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sell Outs</relationshipLabel>
        <relationshipName>Sell_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <globalPicklist>Product_Category</globalPicklist>
        <label>Product Category</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sell Outs</relationshipLabel>
        <relationshipName>Sell_Outs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sell_Out__c</fullName>
        <label>Sell Out</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sell Out</label>
    <nameField>
        <displayFormat>SN-{0000000000}</displayFormat>
        <label>Sell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sell Outs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MEC Dev Sandbox/MEC Dev Sandbox/src/classes/AddSellOutController.cls
public class AddSellOutController {
    
    public String Classification{get;set;}
    public Account RelatedAccount{get;set;}
    public Account Store{get;set;}
    Public List<Account> AccountList {get;set;}
    Map<Id, List<Wrapper>> DisplayMap{get;set;}
    Map<Id, List<SearchWrapper>> DisplaySearchMap{get;set;}
    public boolean returnToAccount{get;set;} 
    public boolean trueBool {get;set;} 
    
    Public List<Wrapper> SearchResult{get;set;}
    Public List<Wrapper> AllSearchResult{get;set;}
    Public List<SearchWrapper> AllSearchCriteria{get;set;}
    Public List<SearchWrapper> SearchCriteria{get;set;}
    public Boolean AddDisabled {get;set;}
    //heree
    public Boolean PrevDisabled {get;set;}
    public Boolean NextDisabled {get;set;}
    Account CurrentAccount {get;set;}
    Integer Index{get;set;}
    
    
    
    public Boolean SearchDisabled {get;set;}
    Account ParentAccount {get;set;}
    
    Pricebook2 stdPb{get;set;}    
    Private Boolean flag{get;set;}
    Private Boolean anotherFlag{get;set;}
    
    
    public AddSellOutController(ApexPages.standardController std) {
        trueBool = true;
        RelatedAccount = (Account)std.getRecord();
        SearchResult = new List<Wrapper>();
        AllSearchResult = new List<Wrapper>();
        DisplayMap = new Map<Id, List<Wrapper>>();
        DisplaySearchMap = new Map<Id, List<SearchWrapper>>();
        SearchCriteria = new List<SearchWrapper>();
        AllSearchCriteria = new List<SearchWrapper>();
        ParentAccount = new Account();
        
        Store = RelatedAccount;
        AddDisabled = True;
        NextDisabled = True;
        PrevDisabled = True;
        Index = 0;
        CurrentAccount = new Account();
        SearchDisabled = True;
        AccountList = new List<Account>();
        
        flag =True;
        anotherFlag = True;
    }
    
    public Class Wrapper{
        public Boolean isSelected {get;set;}
        Public Product2 Prod {get;set;}
        public Account Acc {get;set;}
        public Sell_Out__c sellOut {get;set;} 
        
        Public Wrapper(Boolean isSelected, Account Acc, Product2 Prod){
            this.isSelected = isSelected;
            this.Acc = Acc;
            this.Prod = Prod;
            this.sellOut = sellOut;
        }
    }
    
    @TestVisible
    public Class SearchWrapper{
        public Boolean isSelected {get;set;}
        public String Category {get;set;}
        public String Classification {get;set;}
        Public Id AccId {get;set;}
        Public SearchWrapper(Boolean isSelected, String Category, String Classification, Id AccId){
            this.isSelected = isSelected;
            this.Category = Category;
            this.Classification = Classification;
            this.AccId = AccId;
        }
    }
    
    Public Void getSearchCriteria(){
        AccountList = new List<Account>();
        List<Account> ChildrenAccountList = new List<Account>();
        List<Id> AccountSIdS = new List<Id>();
        //select the current account + its children if any exist
        //if the account parent field filled, then it is a child
        if(RelatedAccount.ParentId != Null){
            AccountList.add(RelatedAccount);
            //ParentAccount = [Select Id, name, Price_Book__c, Parent.Price_Book__c From Account Where Id =: RelatedAccount.ParentId];
        }else{
            //the account is not a child, search if it has children
            AccountList.add(RelatedAccount);
            ChildrenAccountList = [Select Id From Account Where ParentId =: RelatedAccount.Id];
            if(ChildrenAccountList.isEmpty() == False)
                AccountList.addAll(ChildrenAccountList);
        }
        for(Account A : AccountList){
            AccountSIdS.add(A.Id);
        }
        
        List<Customer_Category_Classfication__c> CustomerCategoryClassficationS = [Select Id, Account__c, Classification_Level__c, Product_Category__c From Customer_Category_Classfication__c Where Account__c IN: AccountSIdS];
        //fill AllSearchCriteria wrapper
        AllSearchCriteria = new List<SearchWrapper>();
        for(Customer_Category_Classfication__c ccc: CustomerCategoryClassficationS){
            AllSearchCriteria.add(new SearchWrapper(True, ccc.Product_Category__c, ccc.Classification_Level__c, ccc.Account__c));
        }
        
        //devide AllSearchResult into seperate lists, one for each Account
        List<SearchWrapper> temp = new List<SearchWrapper>();
        for(Account Acc1: AccountList){
            temp = new List<SearchWrapper>();
            for(SearchWrapper w: AllSearchCriteria){
                if(w.AccId == Acc1.Id){
                    temp.add(w);
                }}
            DisplaySearchMap.Put(Acc1.Id, temp);
        }
        
        //system.debug('AllSearchResult ' + AllSearchResult);
        system.debug('DisplaySearchMap ' + DisplaySearchMap);
        
        SearchCriteria = DisplaySearchMap.get(RelatedAccount.Id);
    }
    
    Public void SetAddDisabled(){
        for(Wrapper R: SearchResult){
            if(R.isSelected == True){
                AddDisabled = False;
                break;
            }else{
                AddDisabled = True;
            }
        }
    }
    Public void SetSearchDisabled(){
        for(SearchWrapper R: SearchCriteria){
            if(R.isSelected == True){
                SearchDisabled = False;
                break;
            }else{
                SearchDisabled = True;
            }
        }
    }
    
    Public void SetPrevDisabled(){
        for(Wrapper R: SearchResult){
            if(R.isSelected == True){
                AddDisabled = False;
                break;
            }else{
                AddDisabled = True;
            }
        }
    }
    
    
    Public Void doSearch(){
        DisplayMap = new Map<Id, List<Wrapper>>();
        AccountList = new List<Account>();
        List<Account> ChildrenAccountList = new List<Account>();
        List<Product2> ProductList = new List<Product2>();
        Map<Id, Product2> ProductListToBedisplayed = new Map<Id, Product2>();
        //select the current account + its children if any exist
        //if the account parent field filled, then it is a child
        if(RelatedAccount.ParentId != Null){
            AccountList.add(RelatedAccount);
            ParentAccount = [Select Id, name, Price_Book__c, Parent.Price_Book__c From Account Where Id =: RelatedAccount.ParentId];
        }else{
            //the account is not a child, search if it has children
            AccountList.add(RelatedAccount);
            ChildrenAccountList = [Select Id, name, Price_Book__c, ParentId, Parent.Price_Book__c From Account Where ParentId =: RelatedAccount.Id];
            if(ChildrenAccountList.isEmpty() == False)
                AccountList.addAll(ChildrenAccountList);
        }
        
        List<Id> AccountPricebookEntryIdS = new List<Id>();
        for(Account A: AccountList){
            AccountPricebookEntryIdS.add(A.Price_Book__c);
        }
        
        List<PricebookEntry> AccountPricebookEntry = [Select Product2Id,UnitPrice From PricebookEntry Where pricebook2id IN: AccountPricebookEntryIdS];
        List<Id> ProductSIdS = new List<Id>();
        for(PricebookEntry PEI :AccountPricebookEntry){
            ProductSIdS.add(PEI.Product2Id);
        }
        ProductList = [Select name, Manufacturing_Type__c,Merchandise_Category__c,Product_Hierarchy2__r.Category__c,Item_Status_Description__c,Item_Status__c,
                       Latest_Stock__c From Product2 Where Id IN: ProductSIdS];
        
        List<Product_Classification__c> ProductClassificationS = [Select Product__c, Classification_Level__c From Product_Classification__c Where Product__c IN: ProductSIdS];
        
        //set ProductListToBedisplayed
        for(SearchWrapper SW: SearchCriteria){
            if(SW.isSelected == True){
                for(Product2 prod : ProductList){
                    for(Product_Classification__c PC : ProductClassificationS){
                            if(prod.Id == PC.Product__c && SW.Classification >= PC.Classification_Level__c && SW.Category == Prod.Product_Hierarchy2__r.Category__c ){
                            ProductListToBedisplayed.put(prod.Id, prod); 
                        }
                    }
                }}}
        
        //fill the wrapper
        //Boolean Existing = False;
        Set<Id> ProductIds = new Set<Id>();
        for(Product2 prod : ProductListToBedisplayed.values()){
            ProductIds.add(Prod.Id);
        }
        Account TheParentAcc = New Account(); 
        if(RelatedAccount.ParentId == Null){
            TheParentAcc = RelatedAccount;
        }else{
            TheParentAcc = ParentAccount;
        }
        
        List<PricebookEntry> pbList =  [Select id, pricebook2id, Product2Id, UnitPrice from PricebookEntry WHERE pricebook2id =: TheParentAcc.Price_Book__c AND Product2Id IN: ProductIds];
        
        system.debug('ProductListToBedisplayed.values()' +ProductListToBedisplayed.values());
        AllSearchResult = new List<Wrapper>();
        
        
        for(Account Acc: AccountList){
            for(Product2 P: ProductListToBedisplayed.values()){
                
                //for el list, get same acc and p
                for(PricebookEntry SelectedPb: pbList){
                    if(SelectedPb.Product2Id == p.Id){
                        AllSearchResult.add(new Wrapper(True, Acc, p));
                        break;
                    }
                }
            }
        }
        
        //devide AllSearchResult into seperate lists, one for each Account
        List<Wrapper> temp = new List<Wrapper>();
        for(Account Acc1: AccountList){
            temp = new List<Wrapper>();
            for(Wrapper w: AllSearchResult){
                if(w.Acc.Id == Acc1.Id){
                    temp.add(w);
                }}
            DisplayMap.Put(Acc1.Id, temp);
        }
        
        system.debug('AllSearchResult ' + AllSearchResult);
        system.debug('DisplayMap ' + DisplayMap);
        if (anotherFlag == True){
            Index = 1;
            SearchResult = DisplayMap.get(RelatedAccount.Id);
            if(AccountList.size() > 1){
            NextDisabled = False;
                PrevDisabled = true;}
            
        }
        //CurrentAccount = new Account();
        
        
        
        //if (flag == true) getNextAccount();
        //getNextAccount();
    }
    
    Public Void getNextAccount(){
        anotherFlag = False;
        SearchCriteria = new List<SearchWrapper>();
        SearchResult = new List<Wrapper>();
        List<Wrapper> temp = new List<Wrapper>();
        List<SearchWrapper> Srchtemp = new List<SearchWrapper>();
        if(Index ==1 ) PrevDisabled = False;
        for(Integer i=0 ; i<AccountList.size(); i++){
            if(AccountList[i].Id == CurrentAccount.Id){
                if(i>-1) PrevDisabled = False;
                if(i+1 < AccountList.size()-1){
                    Index = i+1;
                    NextDisabled = False;
                    break;
                }else if(i+1 == AccountList.size()-1){
                    Index = i+1;
                    //setNext Disabled
                    NextDisabled = True;
                    PrevDisabled = False;
                    break;
                }
            }
        }
        system.debug('Index ' + Index);
        CurrentAccount.Id = AccountList[Index].Id;
        Store = AccountList[Index];
        system.debug('hnaaaa '  + Store.name);
        
        if(CurrentAccount.Id != NUll) Srchtemp = DisplaySearchMap.get(CurrentAccount.Id);
        if(Srchtemp.size() > 0){ 
            SearchCriteria.addAll(Srchtemp);
            system.debug('SearchCriteria '  + SearchCriteria);
            
        }else{
            SearchCriteria = DisplaySearchMap.get(RelatedAccount.Id);
        }
        doSearch();
        
        
        if(CurrentAccount.Id != NUll) 
            temp = DisplayMap.get(CurrentAccount.Id);
        
        if(temp.size() >0){ 
            SearchResult.addAll(temp);
        }else{
            SearchResult = new List<Wrapper>();
        }
        
        system.debug('temp ' + temp);
        system.debug('SearchResult ' + SearchResult);
    }
    
    Public void getPrevAccount(){
        SearchCriteria = new List<SearchWrapper>();
        SearchResult = new List<Wrapper>();
        List<Wrapper> temp = new List<Wrapper>();
        List<SearchWrapper> Srchtemp = new List<SearchWrapper>();
        for(Integer i=0 ; i<AccountList.size(); i++){
            if(AccountList[i].Id == CurrentAccount.Id){
                if(i<AccountList.size())NextDisabled = False;
                if(i-1 > 0){
                    Index = i-1;
                    PrevDisabled = False;
                    break;
                }else if(i-1 == 0){
                    Index = i-1;
                    //set previous Disabled
                    PrevDisabled = True;
                    NextDisabled = False;
                    break;
                }
            }
        }
        system.debug('Index ' + Index);
        CurrentAccount.Id = AccountList[Index].Id;
        Store = AccountList[Index];
        system.debug('hnaaaa '  + Store.name);
        
        if(CurrentAccount.Id != NUll) Srchtemp = DisplaySearchMap.get(CurrentAccount.Id);
        if(Srchtemp.size() > 0){ 
            SearchCriteria.addAll(Srchtemp);
            
        }else{
            SearchCriteria = DisplaySearchMap.get(RelatedAccount.Id);
        }
        doSearch();
        
        if(CurrentAccount.Id != NUll)
            temp = DisplayMap.get(CurrentAccount.Id);
        
        if(temp.size() >0){
            SearchResult.addAll(temp);
        }else{
            SearchResult = new List<Wrapper>();
        }
        
        system.debug('temp ' + temp);
        system.debug('SearchResult ' + SearchResult);
    }
    
    Public PageReference AddSellOutsReturn(){
        AddSellOuts();
        return new PageReference('/'+RelatedAccount.id);
    }
    Public PageReference AddSellOuts(){
        //create Opportunity Product Fields
        List<Sell_out__c> sellOutToBeAdded = new List<Sell_out__c>();
        
        Set<Id> ProductIds = new Set<Id>();
        Set<Id> AccountIds = new Set<Id>();
        //get SearchResult Acc.Price_Book__c and Prod.Id
        for(Wrapper RW: SearchResult){
            if(RW.isSelected == True){
                AccountIds.add(RW.Acc.Id);
                //if(RW.Acc.Price_Book__c != Null)
                 //   AccountSPriceBookIds.add(RW.Acc.Price_Book__c);
                //if the Relatedacc is a child account, add the parent account to this list
                //if(RW.Acc.ParentId != Null){
                //    AccountSPriceBookIds.add(ParentAccount.Price_Book__c);
               // }
                //if(RW.Acc.Parent.Price_Book__c != Null) AccountSPriceBookIds.add(RW.Acc.Parent.Price_Book__c);
                ProductIds.add(RW.Prod.Id);
            }
        }
        
        //get related Product_Mapping__c
        List<Product_Mapping__c> RelatedProductMapping =[Select code__c, Account__c, Product__c From Product_Mapping__c Where Account__c IN: AccountIds AND Product__c IN: ProductIds];
        Product_Mapping__c SelectedPM = new Product_Mapping__c();
        //get standard Pricebook
        stdPb = [select Id from Pricebook2 where isStandard=true limit 1];
        
        /* Samy Comment start from here 
        List<PricebookEntry> pbList =  [Select id, pricebook2id, Product2Id,UnitPrice from PricebookEntry WHERE pricebook2id IN: AccountSPriceBookIds AND Product2Id IN: ProductIds];
        //List<PricebookEntry> StandardpbList = [Select id, pricebook2id, Product2Id from PricebookEntry WHERE pricebook2id =: stdPb.id AND Product2Id IN: ProductIds];
        PricebookEntry SelectedPb = new PricebookEntry();
        
        for(Wrapper RW: SearchResult){
            SelectedPM = new Product_Mapping__c();
            NewOppLineItem = new OpportunityLineItem();
            SelectedPb = new PricebookEntry();
            if(RW.isSelected == True){
                NewOppLineItem = RW.opLineItem;
                if(RW.opLineItem.id==null)
                    NewOppLineItem.OpportunityID = RelatedOpp.Id;
                NewOppLineItem.Outlet__c = RW.Acc.Id;
                if(RW.opLineItem.id==null)
                    NewOppLineItem.Product_Id__c = RW.Prod.Id;
                if(RelatedOpp.RecordType.DeveloperName == 'RFPO'){
                    NewOppLineItem.Quantity = RW.opLineItem.RFPO_Qty__c;
                }else if(RelatedOpp.RecordType.DeveloperName == 'PO'){
                    NewOppLineItem.Quantity = RW.opLineItem.PO_Qty__c;
                }
                
                for(Product_Mapping__c PM: RelatedProductMapping){
                    if(PM.Product__c == RW.Prod.Id && PM.Account__c == RW.Acc.Id){
                    SelectedPM = PM;
                        break;
                    }}
                
                //fill conga fields
                if(SelectedPM.Id != Null) NewOppLineItem.Product_Mapping_code__c = SelectedPM.code__c;
                NewOppLineItem.Weighted_Sell_Out__c = RW.sellout.Weighted_Sell_Out__c;
                NewOppLineItem.Sell_Out_Stock_on_Hand__c = RW.sellout.Stock_on_Hand__c; 
                
                
                
                //end heree
                system.debug('NewOppLineItem ' + NewOppLineItem);
                if(NewOppLineItem.PO_Qty__c == Null && NewOppLineItem.RFPO_Qty__c == Null){
                    //don't add    
                }else{
                    OppLineItemToBeAdded.add(NewOppLineItem);
                }
                
            }
        }
        
        
        system.debug('OppLineItemToBeAdded ' + OppLineItemToBeAdded);
        if(OppLineItemToBeAdded.isEmpty() == False)
            upsert OppLineItemToBeAdded;
        */
        
        return null;
    }
    
    
}